version: '3.8'

services:
  app:
    build: .
    command: ["./wait-for-it.sh", "db:3306", "--", "python", "-m", "pytest", "tests"]
    ports:
      - "8000:8000"
    environment:
      - EXAMPLE_ENV_VAR=value
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=ling_classifier
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    networks:
      - default

  db:
    image: mysql:5.7
    container_name: db
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ling_classifier
    volumes:
      - ./data:/docker-entrypoint-initdb.d:ro
    networks:
      - default

networks:
  default:
    driver: bridge
