version: '2'
services:
  app:
    build: .
    links:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=32000
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=ling_classifier

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ling_classifier
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h db --silent"]
      interval: 30s
      timeout: 10s
      retries: 5
