version: '3.8'

services:
  app:
    build: .
    command: ["python", "-m", "pytest", "tests"]
    links:
      - db
    ports:
      - "8000:8000"
    environment:
      - EXAMPLE_ENV_VAR=value
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=ling_classifier
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ling_classifier
    volumes:
      - ./data:/docker-entrypoint-initdb.d:ro

volumes:
  data:
