version: '3.8'

services:
  app:
    build: .
    command: ["flask", "run", "--host=0.0.0.0"]
    environment:
      - FLASK_APP=Web/app.py
      - FLASK_ENV=development
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=ling_classifier
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ling_classifier
    ports:
      - "3306:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost --silent"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  data:
