name: Ling 508 Project Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/docker
            ~/.docker/buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: |
          docker-compose build

      - name: Run Docker Compose
        run: |
          docker-compose up -d

      - name: Run tests
        run: |
          docker-compose run app pytest

      - name: Stop and remove Docker Compose services
        run: |
          docker-compose down
