name: Ling 508 Project Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        run: |
          docker-compose build

      - name: Start Docker Compose services
        run: |
          docker-compose up -d

      - name: Print Docker Compose logs
        run: |
          docker-compose logs

      - name: Stop and remove Docker Compose services
        run: |
          docker-compose down
